version: '3'
services:
  openresty:
    image: openresty/openresty:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./html:/usr/local/openresty/nginx/html
      - ./logs:/usr/local/openresty/nginx/logs
    restart: always
