apiVersion: v1
kind: Service
metadata:
  labels:
    k8s.kuboard.cn/layer: cloud
    k8s.kuboard.cn/name: {{ .Values.redis.name }}
  name: {{ .Values.redis.name }}
  namespace: {{ .Values.kubernetes.namespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: {{ .Values.redis.name }}
      port: {{ .Values.redis.port }}
      protocol: TCP
      targetPort: {{ .Values.redis.port }}
  selector:
    k8s.kuboard.cn/layer: cloud
    k8s.kuboard.cn/name: {{ .Values.redis.name }}
  sessionAffinity: None
  type: ClusterIP
