version: '3'
services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=Gysk@135.com
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /data/minio/data:/data
    command: server /data --console-address ":9001"