{{- if eq .Values.useStatefulSet true }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv
  namespace: {{ .Values.kubernetes.namespace }}
spec:
  capacity:
    storage: {{ .Values.nfs.storage }}
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  nfs:
    path: {{ .Values.nfs.path }}/{{ .Values.kubernetes.namespace }}/{{ .Release.Name }}
    server: {{ .Values.nfs.server }}
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
  namespace: {{ .Values.kubernetes.namespace }}
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.nfs.storage }}
  volumeName: {{ .Release.Name }}-pv
{{- end }}