{{- if eq .Values.useStatefulSet false }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    k8s.kuboard.cn/displayName: {{ .Release.Name }}
    k8s.kuboard.cn/workload: {{ .Release.Name }}
  labels:
    {{- include "kube.labels" . | nindent 4 }}
  name: {{ .Release.Name }}
  namespace: {{ .Values.kubernetes.namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      {{- include "kube.labels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "kube.labels" . | nindent 8 }}
    spec:
      containers:
        - args:
            {{- include "container.args" . | nindent 12 }}
          command:
            - java
          image: {{ include "container.image" . }}
          imagePullPolicy: Always
          name: {{ .Release.Name }}
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 1Gi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
{{- end }}