apiVersion: v1
kind: Service
metadata:
  annotations:
    k8s.kuboard.cn/workload: {{ .Release.Name }}
  labels:
    {{- include "kube.labels" . | nindent 4 }}
  name: {{ .Release.Name }}
  namespace: {{ .Values.kubernetes.namespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: {{ .Release.Name }}
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "kube.labels" . | nindent 4 }}
  sessionAffinity: None
  type: {{ .Values.service.type }}