---
- name: fetch time
  shell: date '+%Y%m%d'
  register: "xunjian_time"

- name: fetch latest file name
  shell: ls -t {{ xunjian_scan_result_file }}|grep {{ xunjian_time.stdout }}|head -n 1
  register: "latest_file"

- name: find files
  find:
    paths: "{{ xunjian_scan_result_file }}"
#    age: "-3d"
    recurse: "yes"
    file_type: "file"
    patterns: "{{ latest_file.stdout }}"
  register: "find_result"

- name: fetch files
  fetch:
    flat: "yes"
    src: "{{ item.path }}"
    dest: "./xunjian-result/{{ xunjian_time.stdout }}/"
  with_items:
    - "{{ find_result.files }}"